kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: crud-test
  namespace: app-news
  labels:
    app: crud-test
    app.kubernetes.io/part-of: crud-test-app
spec:
  host: crud-test-app-news.apps.ocp4.virtus-lab.net
  to:
    kind: Service
    name: crud-test
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
