kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: phpmyadmin
  namespace: app-news
  labels:
    app: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
spec:
  host: phpmyadmin-app-news.apps.ocp4.virtus-lab.net
  to:
    kind: Service
    name: phpmyadmin
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
