apiVersion: v1
kind: Service
metadata:
  name: entry-db-primary
  namespace: app-news
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ExternalName
  externalName: 10.100.24.144