kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpmyadmin
  namespace: app-news
  labels:
    app: phpmyadmin
    app.kubernetes.io/part-of: crud-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        deployment: phpmyadmin
    spec:
      serviceAccountName: phpmyadmin
      containers:
        - name: phpmyadmin
          image: 'image-registry.openshift-image-registry.svc:5000/app-news/phpmyadmin@sha256:af82e8578f1895ab462adc77f8c85a98d50cb56ab0e045c62939b49912047bde'
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: phpmyadmin-env
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
